local list = {
    Enum.KeyCode.Q,
    Enum.KeyCode.W,
    Enum.KeyCode.E,
    Enum.KeyCode.R,
    Enum.KeyCode.T,
    Enum.KeyCode.Y,
    Enum.KeyCode.U,
    Enum.KeyCode.I,
    Enum.KeyCode.O,
    Enum.KeyCode.P,
    Enum.KeyCode.A,
    Enum.KeyCode.S,
    Enum.KeyCode.D,
    Enum.KeyCode.F,
    Enum.KeyCode.G,
    Enum.KeyCode.H,
    Enum.KeyCode.J,
    Enum.KeyCode.K,
    Enum.KeyCode.L,
    Enum.KeyCode.Z,
    Enum.KeyCode.X,
    Enum.KeyCode.C,
    Enum.KeyCode.V,
    Enum.KeyCode.B,
    Enum.KeyCode.N,
    Enum.KeyCode.M,
}

return list